version: '3.1'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    networks:
      - webgateway
      - default
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DEBUG: 'recordWorkout:*'
      DOMAIN: 'http://api.${DOMAIN}'
      EXPIRE_TOKEN: 2h
      EXPIRE_REFRESH: 7d
      HS512_TOKEN: hedfednedve
      HS512_REFRESH: jekfdeldliafdf
      JWT_PRIVATE: "-----BEGIN RSA PRIVATE KEY-----\nMIIJKwIBAAKCAgEArsfz8wnXuQ2cmRabr3ClNljjjEZWH1SHR/lzOZnL6PGvj1cd\nTU1UmJDq/pnpSgJAG39SOgTgsB7vdGUJCr0uEdfJR2vOwDQ6LeScTtbRWCGxwiQ9\nxwpcPK95SG+KdQ1kTVphS3QgVRGas2GNoqv5L3yWbXPFp4o+doS6zFUD2z+RIIcT\n4iy5RVtXklNkyZmgghXGohZzrIlO+s4SswDmcjJOeNdo15tbAuX/yVz89k9cr69k\nKxxi2qNBZe93PJqVtcpxh3RKMFUKRc+JrkqyGJsDGqWvWLDyYV3R7dqqMgOtHwDA\nZ9Y53GfT6s6OdVG3Qj7G3/irSCs/nxNXNX7YGhD46JUrm/9UBV3TyejFV388kjZK\nySFjnffjTnixM8ts4OVT+0yduIPAtwXmrm0kjCnnqBb1oJpZKXB9wl8ZO36F2Qo3\nZQkhsl2jOGBVBROLhlw3epYHy3L4WKJbxOl2GvS1zk8531fmZb+y0S+ldjLjPJ+l\nrfNcRnq6VHSmIZXfbmtPHAPEqHfoBfEHIglfYFbasNmQV8Y2Nr13Xb6v0cX6eTAy\n7L/2CfWzWYtXjwM928dNOy5crp+JorLXd1J1XDB/P3jbH3DYMQh9NHqd0o7fa1lt\ne45/QJYPlLk3KFRWYhDErsLWhcSiHQV8W07WUnrcbnk0qlLz+1MTW3odMZECAwEA\nAQKCAgEAmlz8hmTmAokUClzeSTdKotIkveoM/ASyqg2VB4VegzCZZhaBSZmHomsz\nMIOMd5G/PsnXPGi8bLAVug3Vy4dDnfyfxxVe93/o9klXB4ZQQ+8WSKmrahQrXGl5\ny1C/zxtxv6OYFITOXXN71vvMlKQgIyF81dQO+CZvfktBk19uVYAx07GZDQOE6c1/\nbTt741VsXhePY+5CYVqvx3CjMTcVUDw/9BgDf5C0871giF45B+0VphBYfn7Gi+Tt\nyHKTM5IvsOvIEuLQ9xjURs3CAo3z9ylIt4snb0Rv/TBYTSL3d86pYp1OUSbx2UhV\n8KZXSSRPnxFEoeDEnaucuAjj19pcTkoy+ia1S90zhPT9GvLlfSHAJvKJz52ryeov\n2WPg1WjlG2X10jF5NpHWmB/rckk0NEWLbVHsbZD0p55tdiqOcYEgbhEBgA1H8Nc/\ndGwThmVCgCaZNBXDMeAk9Oh0x8xIiAQr1CoDEmFWTGMu2gEf0viW7R9riHOaLcu8\nZKHebkZ8lTcBh7uqb+OxSNu2MBX1fEbrTJIuJVNh5N3lYtvDflgZ6V+TnLlfGSJD\np/wapR8PpTsOM0YmXunmM2iM8+bfykI0GcqrZbqBTXt40tn5z6sB2DOGvIb9+O/9\nmUjSjO3hwC/7hEm1rmBMmgMHcd1Ss9NchvLetusD7/IQ0ZtguxUCggEBAOaI3VsU\nyTNc5mJlUVoseXO7KAwx4l1dKPKAXEFQJ115rRQda6m4JO0ZbbqkH83v8POLTVc4\nZs1K9oi6Fd9SoZE7dfMXsRz1RuFN7rA5s+6yBpICIbvVuk9tGwtF/8pcnyA1HXBm\nN3QEkOfREke0lZDIj2OQ6IJpE6F+y6zvGfApyY6fkCc5ttHYZWRHqtTGuoamqZTA\nwlWVGQ3ajmCFkt1uT7U9/h4dKHJvbb2m8zP5mGw2qerSaiPng4umd5vyiJeO9QcD\nGpC0LzYen9hBpYsIaYFUO8pnfjsfLTO3lFDKOi9wm6QTjYr1FhMhLWp1sszJwlAV\nInTfAANP3X77MysCggEBAMIWeGuI6uhziRxtBB29xqxnXYeZBtw/Ws6LQzD+89bs\nqyVaUJrPWxhQQxqnkfDKviv7S5X5orSOZKPeWZVjPKMkOKam+LeAafxJEILbSPeO\nM9TDovUm1sFn2BnqMv+dueN/NS+FXWqGRlznJk7v34DpOdPIWDxPh1WloN/wUHBw\n76HoLYneqFNn3Ycjtxs8ycK03miBMe1yNdlavObVoaIM381Qpvo3hOn7oNP9W49Y\nDv6roUA+AhXtzxG/bAwjnWmzaPjr+kmifyvWmj9q5rE0hf0qvcUv/g4lmfZhJ4Td\nXR6Su3U6kostGUbV2RSJGMTag5Q9+Wmdf4LV5ak2ADMCggEBAJy+0kLrjyHtOHgO\ni5HUS3/08PXZtR/mB8FapV+DMEDOSnAy0NFE81aCw6jzjuxnCF2PibaUEtHi9l1g\nqR5/AHvPAhOXOEWIP/lRE8meckkJoo4EBQvB9juq44h2v8TH1SoA81NJLMslj6EO\n9m7qygb3VwdLr8t7xm032SRsLiatQu5Gb608AKINkGLul6i0tn53MzaBGaE3DyHs\nSII4T/Ne3bNNw0qWaLnmKaeZrCLawlhRkpanGqPu9fIt7YWLEnR6Lv/ljFp3KOKT\nT/uqJvSxc4sLytuEIr/wIrvXRnDoD0fSOQEGimbA3ZGELW0FOd0kEYqB1DvCpC+c\nTe3YvqECggEBAIwLGqi9CoLfmrdgEfBD1u7fRqVozYJuVF9kLP9VdyxFaNhy6mZJ\n6DkK8OByuOM95yplEI0Oq1AMzqFO9uTLzh0JLbdSE3SUu+TF85v4DhZSDSQgZZzu\ngVbcTxmj21iFvnNgfkfjuxv59xthzkp22pZxssAVd1VNLSGneQUcqW34j3ALz5AD\nkQFdmILCSoTkv9A2IaTWU+g42JIU3ujQjOgY0gObhmBVXxpV7h4IWeB8cZVg0eFA\n3NBl31u2+4dmy1ZRlhTGcLpg/dHr7zCDOiHy/BtIk9WMY4xhpU4ZnCJKd75vscNM\nmCDEUdDCzPf8VFr2MKrubODAPBlzrVsDE/ECggEBAN9I43ALZbCzJMd0wbXqYkMf\n1aLq6BItLJK1EX6o2Rdqvoj+pbaovIeys5AtWsZuqldWnF34Sqt7NmH77ZGl+aVD\nJ7090JNIfpFyDVO/RqY85qvzGN6sBkRTnV2iVE20RjpHzc5MPhbE0K1iKkd6eXc+\nKlLFTAXjIBXJp11KuDrwwyIl8Oj4IMJQ95NFbkNK0LDFcJzpMF/963YheQ1NXAqT\neTRPjUn8br9pfncGb3wJj86kw0Uku0lUZJCqfojZgvcVaaJEAOQzmMmmA5hRTexk\nVgBgBJXcLWcXUACCXX71swJRx5vMRYTpMj7lyIhcvAr7+38OywUokri8DhaTeq4=\n-----END RSA PRIVATE KEY-----"
      MONGODB_ADDON_URI: mongodb://mongo/recordwork
      MONGODB_ADDON_DB: recordwork
      MONGODB_ADDON_PASSWORD: ${DB_PASS}
      MONGODB_ADDON_USER: ${DB_USER}
      MONGO_ADDON_HOST: mongo

      NODE_ENV: development
      ENABLE_CLEAN: 'true'
      PORT: 8383

    labels:
      traefik.enable: 'true'
      traefik.port: 8383
      traefik.acme: 'false'
      traefik.frontend.rule: 'Host:api.${DOMAIN}'
      traefik.docker.network: 'traefikforwebdev_webgateway'
      traefik.frontend.redirect.regex: ''
      traefik.frontend.redirect.replacement: ''

  mongo:
    image: mongo:4
    volumes:
      - "database:/data/db"
    ports:
      - "28018:27017"
    env_file:
      - .env
    environment:
      MONGODB_ADDON_DB: recordwork
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGODB_ADDON_PASSWORD: ${DB_PASS}
      MONGODB_ADDON_USER: ${DB_USER}
    labels:
      traefik.enable: "false"

networks:
  webgateway:
    external:
      name: traefikforwebdev_webgateway

volumes:
  database:
